############################
## CHANGE THESE
############################

baseURL: "https://adamseab.github.io/pokeden-page"
title: pokeden-page

############################
## MODULES
############################

module:
  imports:
    - path: github.com/chrede88/L1nkr

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
