############################
## Author
############################

author:
  name: Dim's Poke Den
  image: magikarpediem.jpg
  greeting: "Welcome to the Den 🫶"
  icon: ":heart_hands:"

############################
## Links
############################

links:
  # - github: https://github.com/adamseab/pokeden-page
  - whatnot: https://www.whatnot.com/s/otcSKYDV
  # - website:
  # - x-twitter:
  - facebook: https://www.facebook.com/people/Dims-PokeDen/61573756907879/
  - instagram: https://instagram.com/dims_pokeden
  # - whatsapp:
  # - email:
  # - discord:
  # - twitch:
  - tiktok: https://www.tiktok.com/@dims.pokeden
  # - youtube:
  # - snapchat:
  # - etsy:
  # - spotify:
  # - apple:
  # - amazon:
  # - google:
  # - paypal:

############################
## Colunms of Links
############################

# between 2 & 6 columns are supported (both incl)
columns: 2

###########################
## Icon text
###########################

# add the icon name to each icon
icontext: false

############################
## Tooltips
############################

# add tooltips on all icons
tooltip: false

###############################
## OpenGraph & Twitter Cards
###############################

title: Dim's Poké Den
description: "Link tree for Dim's Poké Den - on Whatnot and based in Morriston, Swansea!"
images:
  - magikarpediem.jpg
